services:
  postgres:
    image: postgres:latest
    container_name: chain-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: chainlink
      POSTGRES_DB: chainlink
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chainlink:
    image: smartcontract/chainlink:2.17.0
    container_name: chainlink-compose
    platform: linux/x86_64/v8
    ports:
      - "6688:6688"
    volumes:
      - ../chainlink-sepolia:/chainlink
    depends_on:
      - postgres
    command: ["node", "-config", "/chainlink/config.toml", "-secrets", "/chainlink/secrets.toml", "start","-a", "/chainlink/.api"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
